name: Go Tests

on:
  push:
    branches:
      - master
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - ".golangci.yml"
      - ".github/workflows/test.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - ".golangci.yml"
      - ".github/workflows/test.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Verify formatting
        run: |
          go fmt ./...
          git diff --exit-code

      - name: Install lint tools
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@v0.8.1
          go install github.com/gordonklaus/ineffassign@v0.2.0

      - name: Run lint checks
        run: make lint

      - name: RunTests
        run: go test ./...
